In [3]:
# Generate marks data

from  random import randint

def generatemarks(n,lb,ub):
    filename = "Data Files/marks.txt"
    with open(filename,'w')as f:
        for i in range(n):
            marks = randint(lb,ub)
            f.write(str(marks)+"\n")
    return
generatemarks(100,0,100)

In [3]:
# Function to encript a data file
keyfile = "Data Files/key.txt"
def dictionarykeyfile(keyfile):
    key = {}
    with open(keyfile, 'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
# dictionary key file (keyfile)
def encriptmarksdata(datafile, keyfile):
    key = dictionarykeyfile(keyfile)
    with open(datafile,'r') as f:
        filedata = f.read().split("\n")
    with open("Data Files/Encriptedmarks.txt", 'w')as f:
        for mark in filedata:
            line = ' '
            for n in mark:
                line+=key[n]
            f.write(line +'\n')
    return
datafile = "Data Files/marks.txt"
encriptmarksdata(datafile,keyfile)

In [4]:
# Function to discription a data file
keyfile = "Data Files/key.txt"
# dictionary key file (keyfile)
def discriptmarksdata(Encriptedfile, keyfile):
    key = dictionarykeyfile(keyfile)
    key = key.items()
    newkey = {}
    for i,j in key.items:
        newkey[value] = key
    with open(Encriptedfile,'r') as f:
        Encripteddata = f.read().split("\n")
    with open("Data Files/discriptedmarks.txt", 'w')as f:
        for mark in Encripteddata:
            line = ' '
            for n in Encriptedmark:
                line += newkey
            f.write(line +'\n')
    return
Encriptedfile = "Data Files/marks.txt"
discriptmarksdata(Encriptedfile,keyfile)

AttributeError: 'dict_items' object has no attribute 'items'

In [ ]:
# Comprehensions

keyfile = "Data Files/key.txt"
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key}
evenkeys

### Libraries    Data Sciences


##### Numpy:

* To process N-Dimensional arrays

In [4]:
import numpy as np
li = [1,2,3]
a = np.array(li)
a

array([1, 2, 3])

In [5]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)  # to give a string
a

array(['1', '2', '3', 'z'], dtype='<U11')

In [6]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
b=np.arange(10)  # For range
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
rn = np.random.randint(0,100, size = 10)
rn

array([81, 89, 85,  7, 30, 55, 21, 40, 41, 86])

In [11]:
n3 = np.random.randint(0,2,size =(3,3))
print(n3)

[[0 0 0]
 [0 0 0]
 [1 0 1]]


In [9]:
n3 = np.random.randint(0,2,size=(3,3,3,3))
n3
#n3[2][2][2][1]

array([[[[1, 1, 0],
         [0, 0, 1],
         [1, 0, 0]],

        [[1, 0, 0],
         [0, 0, 0],
         [1, 1, 0]],

        [[1, 0, 0],
         [1, 0, 0],
         [1, 1, 0]]],


       [[[0, 1, 1],
         [1, 0, 1],
         [1, 0, 1]],

        [[1, 1, 1],
         [0, 1, 1],
         [1, 0, 0]],

        [[1, 0, 1],
         [0, 1, 0],
         [1, 0, 0]]],


       [[[1, 0, 1],
         [1, 0, 1],
         [0, 0, 0]],

        [[0, 1, 1],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 1],
         [1, 1, 0],
         [0, 1, 1]]]])

In [16]:
n3.ndim
n3.size   # 3^4  Size ==3 and dim ==4

9

In [ ]:
n3.shape   # (3,3,3,3)
n3.dtype   # dtype('int32')
n3.itemsize  # 4
                            # [2,-1] means 3rd row last element


In [ ]:
n3 = np.random.randint(0,2,size =(3,3))
n3[::-1, ::-1]



In [ ]:
print(b)
b.reshape(5,3)

#### Spliting


In [ ]:
x=[1,2,3,99,99,1,2,3]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

In [ ]:
import numpy as np
M = np.ones((3,3))
print("Matrix M \n",M)

In [ ]:
# for an array it is better to go for broadcasting

#a =[[1 2 3]
 #    [2 3 6]]             e = [1 2 3]
    
#a+e = [[2 4 9]
#        [3 5 9]]

### Pandas

USe cases

Name of the library for 

- Data cleaning
- Data transformation
- Data analysis

**Notations**
- Series      # Row
- DataFrame   # Table   - 

To represent a table best datastructure is dicgtionary


In [6]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':24}
internal1 = pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [8]:
internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2


s1    15
s2    18
s3    12
dtype: int64

In [15]:
final = {'internal1':internal1,'internal2': internal2}

final = pd.DataFrame(final)
final

internal1  internal2
s1         21         15
s2         18         18
s3         24         12

In [17]:
final.columns # All Columns


Index(['internal1', 'internal2'], dtype='object')

In [18]:
final.values    # To get the list all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [37]:
final.values[2,0] = 25  # s3 internal1
final.values[2][0]      #s3 =25 will be assigned

25

In [36]:
for row in final.values:
    print('internal1-'row[0]',internal2-' row[1])

SyntaxError: invalid syntax (<ipython-input-36-5b82d1e34cc5>, line 2)

In [29]:
final.loc['s4']=[15,18]
final

internal1  internal2
s1         21         15
s2         18         18
s3         24         12
3          15         18
s4         15         18

In [34]:
final.drop(3)


internal1  internal2
s1         21         15
s2         18         18
s3         24         12
s4         15         18

In [38]:
final=final.drop(3)
final

internal1  internal2
s1         21         15
s2         18         18
s3         25         12
s4         15         18

In [42]:
final.values[2] = [12,25]
final

internal1  internal2
s1         21         15
s2         18         18
s3         12         25
s4         15         18

In [49]:
# Reading csv file data

import pandas as pd
filepath ="Data Files/Income.csv"
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [50]:
# Extract income of all states in 2013

# California : 57528

for row in incomedf.values:
    print(row[1],':', row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [53]:
# Average income of Arizona

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [54]:
# Average of all states income in 2012

sum = 0
for row in incomedf.values:
    sum += row[-2]
sum/len(incomedf.values)

50038.8

In [2]:

with open('DataFiles/medium-input.txt', 'r') as f:
    t = int(f.readline())
    for i in range(t):
        f.readline()
        li =  list(map(int,f.readline().split()))
        k = int(f.readline())
        print(max(li)-k+1)


FileNotFoundError: [Errno 2] No such file or directory: 'DataFiles/medium-input.txt'